#!/usr/bin/env bash
# Re-answer (重答) the medical prompts with DeepSeek-V4-Flash served at :3333.
# Input : {id, conversations:[system,user]} (perfectblend structure)
# Output: {id, conversations:[system,user,assistant]}  (assistant regenerated by V4-Flash)
set -euo pipefail

DEEPSPEC_ROOT=/shenlb/zwf-spec/train-v1/deepspec
GEN=${DEEPSPEC_ROOT}/scripts/data/generate_train_data-dsk-v4-flash.py

# --- DeepSeek-V4-Flash inference service (OpenAI-compatible, deployed by you) ---
model_name=DeepSeek-V4-Flash-DSpark          # matches /v1/models on :3333
server_addresses=(127.0.0.1:3333 127.0.0.1:3335 127.0.0.1:3336 127.0.0.1:3337)

# --- I/O ---
input_file_path=/shenlb/zwf-spec/dataset/dataset-v1/主agent输入_医疗助手_正式环境_perfectblend_ctx2user.jsonl
output_file_path=/shenlb/zwf-spec/dataset/dataset-v1/主agent输入_医疗助手_正式环境_perfectblend_ctx2user_regen.jsonl

# --- sampling ---
concurrency=32
temperature=0.7
top_p=0.8
top_k=20
min_p=0
max_tokens=4096

echo "Re-answering ${input_file_path}"
echo "  via DeepSeek-V4-Flash @ ${server_addresses[*]}  ->  ${output_file_path}"
python "${GEN}" \
    --model "${model_name}" \
    --server-address "${server_addresses[@]}" \
    --input-file-path "${input_file_path}" \
    --output-file-path "${output_file_path}" \
    --concurrency "${concurrency}" \
    --temperature "${temperature}" \
    --top-p "${top_p}" \
    --top-k "${top_k}" \
    --min-p "${min_p}" \
    --max-tokens "${max_tokens}" \
    --resume \
    "$@"
